POST http://localhost:8080   HTTP/1.1
content-type: application/json

{
   "deleted":false,
   "email":false,
   "payload":{
      "description":"",
      "analysisresultsfolder":"/iplant/home/ipcdev/analyses_qa/Copy_of_NanoDJ_analysis1-2020-10-16-21-07-37.7",
      "name":"Copy_of_NanoDJ_analysis1",
      "username":"ipcdev@iplantcollaborative.org",
      "app_id":"57712906-d5e7-11e9-869a-008cfa5ae621",
      "analysisstartdate":"2020-10-16T21:07:42.157Z",
      "system_id":"de",
      "app_disabled":false,
      "analysisstatus":"Submitted",
      "batch":false,
      "status":"Submitted",
      "id":"a13bc61c-0ff3-11eb-a36d-62d47aced14b",
      "analysisname":"Copy_of_NanoDJ_analysis1",
      "startdate":"1602882462157",
      "app_description":"A Dockerized Jupyter Notebook for Interactive Oxford Nanopore MinION Sequence Manipulation and Genome Assembly",
      "action":"job_status_change",
      "analysisdescription":"",
      "notify":true,
      "resultfolderid":"/iplant/home/ipcdev/analyses_qa/Copy_of_NanoDJ_analysis1-2020-10-16-21-07-37.7",
      "email_address":"core-sw@iplantcollaborative.org",
      "user":"ipcdev",
      "app_name":"Copy of NanoDJ"
   },
   "email_template":"analysis_status_change",
   "type":"analysis",
   "seen":false,
   "user":"ipcdev",
   "subject":"Copy_of_NanoDJ_analysis1 status changed.",
   "message":{
      "id":"DE24C5EF-68A2-462D-B3FC-B1F06C7AA11B",
      "timestamp":"1602882462337",
      "text":"Copy_of_NanoDJ_analysis1 submitted"
   }
}